export const ERROR_CODES = Object.freeze({
    FORBIDDEN: "FORBIDDEN",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    SESSION_NAME_REQUIRED: "SESSION_NAME_REQUIRED",
    SESSION_FULL: "SESSION_FULL",
    SESSION_LOCKED: "SESSION_LOCKED",
    DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
    DRIVER_NAME_REQUIRED: "DRIVER_NAME_REQUIRED",
    DRIVER_EXISTS: "DRIVER_EXISTS",
    DRIVER_LOCKED: "DRIVER_LOCKED",
    NO_NEXT_RACE: "NO_NEXT_RACE"
});

export const SUCCESS_CODES = Object.freeze({
    SESSION_ADDED: "SESSION_ADDED",
    SESSION_UPDATED: "SESSION_UPDATED",
    SESSION_DELETED: "SESSION_DELETED",
    DRIVER_ADDED: "DRIVER_ADDED",
    DRIVER_UPDATED: "DRIVER_UPDATED",
    DRIVER_DELETED: "DRIVER_DELETED"
});
