export const ERROR_CODES = Object.freeze({
    FORBIDDEN: "FORBIDDEN",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    SESSION_NAME_REQUIRED: "SESSION_NAME_REQUIRED",
    SESSION_FULL: "SESSION_FULL",
    SESSION_LOCKED: "SESSION_LOCKED",
    SESSION_DRIVERS_REQUIRED: "SESSION_DRIVERS_REQUIRED",
    DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
    DRIVER_NAME_REQUIRED: "DRIVER_NAME_REQUIRED",
    DRIVER_EXISTS: "DRIVER_EXISTS",
    DRIVER_LOCKED: "DRIVER_LOCKED",
    CAR_EXISTS: "CAR_EXISTS",
    CAR_OUT_OF_RANGE: "CAR_OUT_OF_RANGE",
    NO_NEXT_RACE: "NO_NEXT_RACE",
    AT_LEAST_ONE_FIELD_REQUIRED: "AT_LEAST_ONE_FIELD_REQUIRED"
});

export const SUCCESS_CODES = Object.freeze({
    SESSION_ADDED: "SESSION_ADDED",
    SESSION_UPDATED: "SESSION_UPDATED",
    SESSION_DELETED: "SESSION_DELETED",
    SESSION_CONFIRMED: "SESSION_CONFIRMED",
    DRIVER_ADDED: "DRIVER_ADDED",
    DRIVER_UPDATED: "DRIVER_UPDATED",
    DRIVER_DELETED: "DRIVER_DELETED"
});
